name: Recycler
main: de.craftlancer.recycler.Recycler
version: 1.1.0
description: Recycle your useless stuff!
commands:
    recycler:
        description: reloads config
permissions:
    recycler.admin:
        default: op
    recycler.item.<id>:
        default: false
        description: Allows you to recycle Items with Id <id>